name = "pre-commit"
type = "cli"

[platform.macos]
archive-prefix = "pre-commit-{version}"
checksum-file = "pre-commit-{version}.pyz.sha256sum"
download-file = "pre-commit-{version}.pyz"

[platform.linux]
archive-prefix = "pre-commit-{version}"
checksum-file = "pre-commit-{version}.pyz.sha256sum"
download-file = "pre-commit-{version}.pyz"

[platform.windows]
archive-prefix = "pre-commit-{version}"
checksum-file = "pre-commit-{version}.pyz.sha256sum"
download-file = "pre-commit-{version}.pyz"

[install]
unpack = true
checksum-url = "https://github.com/pre-commit/pre-commit/releases/download/v{version}/{checksum_file}"
download-url = "https://github.com/pre-commit/pre-commit/releases/download/v{version}/{download_file}"

[resolve]
git-url = "https://github.com/pre-commit/pre-commit"
